<a href="https://colab.research.google.com/github/Komal05010/CSE-ML-Practicals/blob/main/Practical_03/Practical-03_KNN_Classification_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practical No. 3: Implementation of K-Nearest Neighbors (KNN)

## Aim
To implement the K-Nearest Neighbors (KNN) classification algorithm on the processed dataset using different distance measures and evaluate its performance.

In [40]:
import pandas as pd
import numpy as np

from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

## Dataset Used

The processed dataset obtained from Practical 2 is used as the input dataset.

The five normalized subject marks used as input features (`X`) are:

- Software Engineer
- Theory of Computation (TOC)
- Computer Network
- Machine Learning
- Data Warehouse

The `GRADE` column is used as the target variable (`y`).

The dataset contains **61 student records** and **5 input features**.

In [41]:
uploaded = files.upload()

Saving preprocessed_dataset (1).xlsx to preprocessed_dataset (1) (1).xlsx

In [42]:
# Read Excel file
filename = list(uploaded.keys())[0]
df = pd.read_excel(filename)

In [43]:
print("Dataset shape:", df.shape)

Dataset shape: (61, 9)

In [44]:
print(df.columns)

Index(['ROLL NO.', 'SOFTWARE ENGINEER', 'TOC', 'COMPUTER NETWORK',
       'MACHINE LEARNING', 'DATA WAREHOUSE', 'GRADE', 'RESULT', 'GENDER_Male'],
      dtype='object')

### K-Nearest Neighbors (KNN)

K-Nearest Neighbors is a supervised, non-parametric machine learning algorithm. It does not build an explicit mathematical model during training. Instead, it stores the training data and makes predictions by finding the nearest data points to a given test point.

The basic steps of KNN are:

1. Choose the value of K.
2. Calculate the distance between the test point and all training points.
3. Identify the K nearest neighbors.
4. Determine the most common class among these neighbors.
5. Assign that class to the test point.

In this practical, **K = 7** is used for all three distance measures to ensure a fair comparison.

In [45]:
# Input features
X = df[
    [
        "SOFTWARE ENGINEER",
        "TOC",
        "COMPUTER NETWORK",
        "MACHINE LEARNING",
        "DATA WAREHOUSE"
    ]
]

# Target
y = df["GRADE"]

In [46]:
print("\nFeatures (X):")
display(X.head())

print("\nTarget (y):")
print(y.head())

Features (X):

,SOFTWARE ENGINEER,TOC,COMPUTER NETWORK,MACHINE LEARNING,DATA WAREHOUSE
0,-1.114072,-1.285932,-1.086620,-1.254576,-1.134590
1,-1.114072,-0.382744,0.064141,-0.373918,-0.730562
2,-0.462974,-0.563382,-0.472881,-0.550050,-0.488145
3,1.246160,0.972037,0.984749,1.211265,0.804744
4,-1.114072,-1.285932,-1.086620,-1.254576,-1.134590

Target (y):
0    C
1    B
2    B
3    A
4    C
Name: GRADE, dtype: object

In [47]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (48, 5)
Testing data: (13, 5)

In [48]:
k = 7

knn = KNeighborsClassifier(n_neighbors=k)

knn.fit(X_train, y_train)

print("KNN model trained successfully!")
print("K =", k)

KNN model trained successfully!
K = 7

## 1. Euclidean Distance

Euclidean distance measures the straight-line distance between two points. It is commonly used when the distance between data points is measured in a geometric space.

**Formula:**

$$
d(x,y) =
\sqrt{
\sum_{i=1}^{n}(x_i-y_i)^2
}
$$

In Scikit-learn:

`metric='euclidean'`

In [49]:
knn_euclidean = KNeighborsClassifier(
    n_neighbors=5,
    metric='euclidean'
)
knn_euclidean.fit(X_train, y_train)
y_pred_euclidean = knn_euclidean.predict(X_test)

In [50]:
accuracy_euclidean = accuracy_score(y_test, y_pred_euclidean)
print("Euclidean Distance Accuracy:",
      accuracy_euclidean * 100, "%")

Euclidean Distance Accuracy: 53.84615384615385 %

### Confusion Matrix

A confusion matrix is a table used to evaluate the classification performance of a model. It shows the number of correctly and incorrectly classified samples for each class.

The rows represent the actual classes, while the columns represent the predicted classes.

### Classification Report

The classification report provides:

- **Precision** – proportion of predicted samples that are actually correct.
- **Recall** – proportion of actual samples correctly identified.
- **F1-score** – harmonic mean of precision and recall.
- **Support** – number of actual samples belonging to each class.

In [51]:
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_euclidean))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_euclidean, zero_division=0))

Confusion Matrix:
[[1 0 1 0 0 0]
 [0 1 0 0 0 0]
 [2 0 1 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 3 0]
 [0 0 0 1 0 0]]

Classification Report:
              precision    recall  f1-score   support

           A       0.33      0.50      0.40         2
          A+       1.00      1.00      1.00         1
           B       0.50      0.25      0.33         4
           C       0.25      1.00      0.40         1
           F       1.00      0.75      0.86         4
           P       0.00      0.00      0.00         1

    accuracy                           0.54        13
   macro avg       0.51      0.58      0.50        13
weighted avg       0.61      0.54      0.54        13

## 2. Manhattan Distance

Manhattan distance calculates the distance between two points by adding the absolute differences between their corresponding features.

**Formula:**

$$
d(x,y) =
\sum_{i=1}^{n}|x_i-y_i|
$$

In Scikit-learn:

`metric='manhattan'`

In [52]:
knn_manhattan = KNeighborsClassifier(
    n_neighbors=5,
    metric='manhattan'
)
knn_manhattan.fit(X_train, y_train)
y_pred_manhattan = knn_manhattan.predict(X_test)

In [53]:
accuracy_manhattan = accuracy_score(y_test, y_pred_manhattan)
print("Manhattan Distance Accuracy:",
      accuracy_manhattan * 100, "%")

Manhattan Distance Accuracy: 53.84615384615385 %

In [54]:
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_manhattan))
print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred_manhattan,
    zero_division=0
))

Confusion Matrix:
[[1 0 1 0 0 0]
 [0 1 0 0 0 0]
 [2 0 1 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 1 3 0]
 [0 0 0 1 0 0]]

Classification Report:
              precision    recall  f1-score   support

           A       0.33      0.50      0.40         2
          A+       1.00      1.00      1.00         1
           B       0.50      0.25      0.33         4
           C       0.25      1.00      0.40         1
           F       1.00      0.75      0.86         4
           P       0.00      0.00      0.00         1

    accuracy                           0.54        13
   macro avg       0.51      0.58      0.50        13
weighted avg       0.61      0.54      0.54        13

## 3. Minkowski Distance

Minkowski distance is a generalized distance measure that can represent different distance metrics depending on the value of \(p\).

**Formula:**

$$
d(x,y) =
\left(
\sum_{i=1}^{n}|x_i-y_i|^p
\right)^{1/p}
$$

The value of \(p\) determines the type of distance:

* \(p = 3\) → Minkowski distance used in this practical

In Scikit-learn:

`metric='minkowski', p=3`

In [55]:
knn_minkowski = KNeighborsClassifier(
    n_neighbors=5,
    metric='minkowski',
    p=3
)
knn_minkowski.fit(X_train, y_train)
y_pred_minkowski = knn_minkowski.predict(X_test)

In [56]:
accuracy_minkowski = accuracy_score(y_test, y_pred_minkowski)
print("Minkowski Distance Accuracy:",
      accuracy_minkowski * 100, "%")

Minkowski Distance Accuracy: 61.53846153846154 %

In [57]:
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_minkowski))
print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred_minkowski,
    zero_division=0
))

Confusion Matrix:
[[1 0 1 0 0 0]
 [0 1 0 0 0 0]
 [2 0 1 1 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 4 0]
 [0 0 0 1 0 0]]

Classification Report:
              precision    recall  f1-score   support

           A       0.33      0.50      0.40         2
          A+       1.00      1.00      1.00         1
           B       0.50      0.25      0.33         4
           C       0.33      1.00      0.50         1
           F       1.00      1.00      1.00         4
           P       0.00      0.00      0.00         1

    accuracy                           0.62        13
   macro avg       0.53      0.62      0.54        13
weighted avg       0.62      0.62      0.59        13

### Accuracy

Accuracy represents the proportion of correctly classified samples out of all test samples.

$$
Accuracy =
\frac{Correct\ Predictions}
{Total\ Predictions}
$$

In [58]:
results = pd.DataFrame({
    'Distance': ['Euclidean', 'Manhattan', 'Minkowski'],
    'Accuracy': [
        accuracy_euclidean,
        accuracy_manhattan,
        accuracy_minkowski
    ]
})
results['Accuracy (%)'] = results['Accuracy'] * 100
results

    Distance  Accuracy  Accuracy (%)
0  Euclidean  0.538462     53.846154
1  Manhattan  0.538462     53.846154
2  Minkowski  0.615385     61.538462

In [59]:
best_distance = results.loc[
    results['Accuracy'].idxmax(),
    'Distance'
]
best_accuracy = results['Accuracy (%)'].max()
print("Best Distance:", best_distance)
print("Best Accuracy:", best_accuracy, "%")

Best Distance: Minkowski
Best Accuracy: 61.53846153846154 %

### Conclusion

K-Nearest Neighbors (KNN) was successfully implemented on the processed student dataset using three different distance measures: Euclidean, Manhattan, and Minkowski distance. The five normalized subject marks were used as input features and `GRADE` was used as the target variable.