<a href="https://colab.research.google.com/github/Komal05010/CSE-AIML-Practicals/blob/main/Practical-3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [8]:
uploaded = files.upload()

Saving preprocessed_dataset.xlsx to preprocessed_dataset.xlsx

In [9]:
df = pd.read_excel("preprocessed_dataset.xlsx")

display(df.head())

   ROLL NO.  SOFTWARE ENGINEER       TOC  ...  GRADE  RESULT  GENDER_Male
0 -1.452221          -1.114072 -1.285932  ...      C    PASS         True
1 -1.406793          -1.114072 -0.382744  ...      B    PASS        False
2 -1.361364          -0.462974 -0.563382  ...      B    PASS         True
3 -1.315936           1.246160  0.972037  ...      A    PASS         True
4 -1.270508          -1.114072 -1.285932  ...      C    PASS         True

[5 rows x 9 columns]

In [10]:
print(df.columns.tolist())

['ROLL NO.', 'SOFTWARE ENGINEER', 'TOC', 'COMPUTER NETWORK', 'MACHINE LEARNING', 'DATA WAREHOUSE', 'GRADE', 'RESULT', 'GENDER_Male']

In [11]:
print(df["RESULT"].value_counts())

RESULT
PASS    58
FAIL     3
Name: count, dtype: int64

In [12]:
df["RESULT"] = df["RESULT"].astype("string").str.strip().str.upper()

print(df["RESULT"].unique())

<StringArray>
['PASS', 'FAIL']
Length: 2, dtype: string

In [13]:
print("Numerical columns:")
print(df.select_dtypes(include=np.number).columns.tolist())

Numerical columns:
['ROLL NO.', 'SOFTWARE ENGINEER', 'TOC', 'COMPUTER NETWORK', 'MACHINE LEARNING', 'DATA WAREHOUSE']

In [14]:
features = [
    "ROLL NO.",
    "SOFTWARE ENGINEER",
    "TOC",
    "COMPUTER NETWORK",
    "MACHINE LEARNING",
    "DATA WAREHOUSE"
]

X = df[features]
y = df["RESULT"]

In [15]:
X = X.fillna(X.median())

print(X.isnull().sum())

ROLL NO.             0
SOFTWARE ENGINEER    0
TOC                  0
COMPUTER NETWORK     0
MACHINE LEARNING     0
DATA WAREHOUSE       0
dtype: int64

In [16]:
y = y.map({
    "FAIL": 0,
    "PASS": 1
})

print(y.value_counts())

RESULT
1    58
0     3
Name: count, dtype: int64

In [26]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [27]:
from sklearn.metrics import pairwise_distances

euclidean_matrix = pairwise_distances(
    X_test_scaled,
    X_train_scaled,
    metric="euclidean"
)

manhattan_matrix = pairwise_distances(
    X_test_scaled,
    X_train_scaled,
    metric="manhattan"
)

minkowski_matrix = pairwise_distances(
    X_test_scaled,
    X_train_scaled,
    metric="minkowski",
    p=3
)

In [28]:
print("Euclidean Distance Matrix:")
display(pd.DataFrame(euclidean_matrix))

print("Manhattan Distance Matrix:")
display(pd.DataFrame(manhattan_matrix))

print("Minkowski Distance Matrix (p=3):")
display(pd.DataFrame(minkowski_matrix))

Euclidean Distance Matrix:

          0         1         2   ...        45        46        47
0   1.690170  0.819185  2.758777  ...  2.060631  1.700796  3.458108
1   2.772339  1.268992  2.205083  ...  3.409704  2.298379  2.483154
2   3.750518  3.743085  0.812983  ...  4.821432  4.661768  1.344381
3   1.970951  0.517380  2.821734  ...  2.302216  1.484268  3.403109
4   2.906306  2.264554  4.969860  ...  2.195555  1.964093  5.554007
5   1.581507  2.441857  1.843526  ...  2.476826  3.411952  3.048201
6   2.546610  2.060784  1.178010  ...  3.409556  3.079691  1.833887
7   2.695633  2.623003  0.613795  ...  3.722220  3.547687  1.609968
8   2.237370  0.812734  2.274408  ...  2.798391  1.831479  2.732508
9   2.903738  1.465799  4.050436  ...  2.793564  1.246246  4.428886
10  3.161008  1.403226  4.338294  ...  2.931821  1.071211  4.632807
11  3.601659  3.728413  0.756400  ...  4.671168  4.655960  1.552140
12  5.222276  5.458894  7.895954  ...  4.193661  4.840371  8.614101

[13 rows x 48 columns]

Manhattan Distance Matrix:

           0          1          2   ...         45         46         47
0    2.832756   0.819185   6.436346  ...   4.419538   2.894141   8.216603
1    4.931101   2.441211   4.814320  ...   7.507474   4.516167   5.128667
2    8.973359   9.070370   1.814839  ...  11.549732  11.145326   1.586722
3    3.134561   0.517380   6.738151  ...   4.721343   2.592336   7.914798
4    6.576427   5.358427  11.751658  ...   4.086285   4.232001  12.755845
5    3.333730   4.716725   4.263406  ...   5.730177   6.791681   6.905964
6    5.704403   4.766653   2.656739  ...   8.280776   6.841609   4.355365
7    6.467360   6.219450   1.036081  ...   9.043732   8.294406   3.592408
8    3.879062   1.726626   5.528904  ...   6.275509   3.801583   6.360632
9    4.959985   2.538800   9.794331  ...   4.733010   1.824053  10.022448
10   5.421963   3.341662  10.597193  ...   2.931821   2.106011  10.825310
11   8.507628   9.035788   1.780257  ...  11.084000  11.110745   1.552140
12  12.212870  12.719470  17.474330  ...   9.722727  11.593044  20.116888

[13 rows x 48 columns]

Minkowski Distance Matrix (p=3):

          0         1         2   ...        45        46        47
0   1.577275  0.819185  2.116436  ...  1.726449  1.461692  2.628297
1   2.451914  1.074485  1.779568  ...  2.751735  1.936895  2.032435
2   2.840388  2.804506  0.647389  ...  3.634283  3.533795  1.336894
3   1.871679  0.517380  2.139522  ...  1.992761  1.245940  2.610773
4   2.318662  1.723985  3.771053  ...  2.014585  1.544135  4.244867
5   1.286018  2.181846  1.428446  ...  1.904537  2.896016  2.431370
6   2.015541  1.603158  0.917264  ...  2.551098  2.470013  1.389032
7   2.036623  1.995930  0.541350  ...  2.783006  2.728298  1.308141
8   2.064217  0.640905  1.699921  ...  2.280796  1.491030  2.083480
9   2.656523  1.285440  3.044182  ...  2.647971  1.166956  3.424370
10  2.939397  1.069907  3.227068  ...  2.931821  0.883015  3.527533
11  2.751339  2.791316  0.580456  ...  3.537514  3.529438  1.552140
12  4.014417  4.230627  6.117734  ...  3.266185  3.669183  6.598718

[13 rows x 48 columns]

In [29]:
K = 5

euclidean_neighbours = np.argsort(
    euclidean_matrix,
    axis=1
)[:, :K]

In [30]:
print("Nearest neighbours using Euclidean distance:")
print(euclidean_neighbours)

Nearest neighbours using Euclidean distance:
[[ 8 32  4 23  7]
 [44  1 27  8 30]
 [36 17 21 20 31]
 [ 8  1 23 32  7]
 [15 13 12  5 10]
 [43 27  9 29 11]
 [44 27  2 11 16]
 [ 2 11 16 44 17]
 [23  8 27  1  7]
 [39 26  7 46  1]
 [26  5 13 39 15]
 [36 20 37 17 21]
 [38 12  6 10 42]]

In [32]:
import numpy as np

euclidean_labels = np.asarray(y_train)[euclidean_neighbours]

print("Classes of nearest neighbours:")
print(euclidean_labels)

Classes of nearest neighbours:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 0 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 1 1 1]]

In [34]:
euclidean_predictions = []

for neighbours in euclidean_labels:
    prediction = np.bincount(neighbours).argmax()
    euclidean_predictions.append(prediction)

print("Euclidean predictions:")
print(euclidean_predictions)

Euclidean predictions:
[np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1)]

In [35]:
from sklearn.metrics import accuracy_score

euclidean_accuracy = accuracy_score(
    y_test,
    euclidean_predictions
)

print("Euclidean KNN Accuracy:", euclidean_accuracy)
print("Euclidean KNN Accuracy (%):", euclidean_accuracy * 100)

Euclidean KNN Accuracy: 0.9230769230769231
Euclidean KNN Accuracy (%): 92.3076923076923

In [36]:
K = 5

manhattan_neighbours = np.argsort(
    manhattan_matrix,
    axis=1
)[:, :K]

print("Manhattan nearest neighbours:")
print(manhattan_neighbours)

Manhattan nearest neighbours:
[[ 8 32  1  4 23]
 [27  1 44  8 30]
 [36 21 20 31 17]
 [ 8  1 32 30  7]
 [15 13  5 10 42]
 [43 27 44  9 29]
 [44 27 43 11  2]
 [ 2 11 16 18 44]
 [23  8 27  1 30]
 [39 46  7 26 14]
 [26 40  5 46 13]
 [36 20 37 21 17]
 [38 12  6 10 42]]

In [37]:
manhattan_labels = np.asarray(y_train)[manhattan_neighbours]

print("Classes of Manhattan nearest neighbours:")
print(manhattan_labels)

Classes of Manhattan nearest neighbours:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 1 1 1]]

In [38]:
manhattan_predictions = []

for neighbours in manhattan_labels:
    prediction = np.bincount(neighbours).argmax()
    manhattan_predictions.append(prediction)

print("Manhattan predictions:")
print(manhattan_predictions)

Manhattan predictions:
[np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1)]

In [39]:
manhattan_accuracy = accuracy_score(
    y_test,
    manhattan_predictions
)

print("Manhattan KNN Accuracy:", manhattan_accuracy)
print("Manhattan KNN Accuracy (%):", manhattan_accuracy * 100)

Manhattan KNN Accuracy: 0.9230769230769231
Manhattan KNN Accuracy (%): 92.3076923076923

In [40]:
minkowski_neighbours = np.argsort(
    minkowski_matrix,
    axis=1
)[:, :K]

print("Minkowski nearest neighbours:")
print(minkowski_neighbours)

Minkowski nearest neighbours:
[[ 8 32  4 23  7]
 [44 27  1  8 30]
 [36 17 21 20 16]
 [ 8 23 32  7  1]
 [12 15 13  5 10]
 [43  9 29 27 11]
 [44 27  2 11 34]
 [ 2 11 16 17 44]
 [23  8  1 27  7]
 [26 39  7 46 15]
 [26  5 13 39 15]
 [36 20 37 17  2]
 [38 12  6 10 42]]

In [41]:
minkowski_labels = np.asarray(y_train)[minkowski_neighbours]

print("Classes of Minkowski nearest neighbours:")
print(minkowski_labels)

Classes of Minkowski nearest neighbours:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 1 1 1]]

In [42]:
minkowski_predictions = []

for neighbours in minkowski_labels:
    prediction = np.bincount(neighbours).argmax()
    minkowski_predictions.append(prediction)

print("Minkowski predictions:")
print(minkowski_predictions)

Minkowski predictions:
[np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1)]

In [43]:
minkowski_accuracy = accuracy_score(
    y_test,
    minkowski_predictions
)

print("Minkowski KNN Accuracy:", minkowski_accuracy)
print("Minkowski KNN Accuracy (%):", minkowski_accuracy * 100)

Minkowski KNN Accuracy: 0.9230769230769231
Minkowski KNN Accuracy (%): 92.3076923076923

In [44]:
results = pd.DataFrame({
    "Distance": [
        "Euclidean",
        "Manhattan",
        "Minkowski (p=3)"
    ],
    "Accuracy (%)": [
        euclidean_accuracy * 100,
        manhattan_accuracy * 100,
        minkowski_accuracy * 100
    ]
})

display(results)

          Distance  Accuracy (%)
0        Euclidean     92.307692
1        Manhattan     92.307692
2  Minkowski (p=3)     92.307692

In [45]:
best_distance = results.loc[
    results["Accuracy (%)"].idxmax()
]

print("Best Distance Metric:", best_distance["Distance"])
print("Best Accuracy:", best_distance["Accuracy (%)"], "%")

Best Distance Metric: Euclidean
Best Accuracy: 92.3076923076923 %