<a href="https://colab.research.google.com/github/Komal05010/CSE-ML-Practicals/blob/main/Practical_01_Pandas_Import_Export.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practical 01: Pandas Import and Export

## Aim
To perform data import and export operations using the Pandas library in Python with different file formats such as Excel, CSV, JSON, and TSV.

## Introduction

Pandas is an open-source Python library used for data manipulation and analysis.
It provides powerful data structures such as Series and DataFrame for handling structured data.

A Pandas DataFrame can be imported from and exported to various file formats.
This practical demonstrates the import and export of student data using Excel, CSV, JSON, and TSV formats.

The general workflow is:

**External File → Pandas DataFrame → Processing/Analysis → Exported File**

##1 — Import and read dataset

In [26]:
import os

if os.path.exists("DATASETS/Mldata.xlsx"):
    print("Dataset folder already available.")
else:
    !git clone https://github.com/Komal05010/CSE-ML-Practicals
    %cd CSE-ML-Practicals
    print("Repository cloned successfully.")

Dataset folder already available.

In [27]:
# Practical 01
import pandas as pd

## 2. Importing Data from Excel

The `read_excel()` function is used to read data from an Excel file and store it in a Pandas DataFrame.

In [28]:
df = pd.read_excel(
    "DATASETS/Mldata.xlsx",
    dtype={"ROLL NO.": "string"} #because python was reading roll numbers as some sort of float data type and changing it into scientific notations
)

df

,ROLL NO.,GENDER,SOFTWARE ENGINEER,TOC,COMPUTER NETWORK,MACHINE LEARNING,DATA WAREHOUSE,GRADE,RESULT
0,240104010001,M,30.0,30.0,30.0,30.0,30.0,C,PASS
1,240104010002,F,30.0,40.0,45.0,40.0,35.0,B,Pass
2,240104010003,M,38.0,38.0,38.0,38.0,38.0,B,Pass
3,240104010004,M,59.0,55.0,57.0,58.0,54.0,A,pass
4,240104010005,M,30.0,30.0,30.0,30.0,30.0,C,Pass
...,...,...,...,...,...,...,...,...,...
81,2520104004,M,24.0,25.0,26.0,27.0,24.0,P,Pass
82,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,2520104006,F,30.0,30.0,30.0,30.0,30.0,B,Pass
84,2520104007,F,45.0,40.0,50.0,48.0,46.0,A,pass
85,2520104008,F,35.0,30.0,40.0,45.0,48.0,B,Pass

## 3. Exporting Data to Excel

The `to_excel()` function is used to export a Pandas DataFrame into an Excel file.

In [29]:
df.to_excel("EXPORTS/Mldata_export.xlsx", index=False)

print("Data exported successfully to Excel.")

Data exported successfully to Excel.

## 4. Exporting Data to CSV

The `to_csv()` function is used to export the DataFrame into a CSV (Comma-Separated Values) file.

The parameter `index=False` prevents the Pandas index from being written as an additional column.

In [30]:
df.to_csv("EXPORTS/Mldata.csv", index=False)

print("Data exported successfully to CSV.")

Data exported successfully to CSV.

### Importing the CSV File

In [31]:
df_csv = pd.read_csv(
    "EXPORTS/Mldata.csv",
    dtype={"ROLL NO.":"string"}
)

df_csv

,ROLL NO.,GENDER,SOFTWARE ENGINEER,TOC,COMPUTER NETWORK,MACHINE LEARNING,DATA WAREHOUSE,GRADE,RESULT
0,240104010001,M,30.0,30.0,30.0,30.0,30.0,C,PASS
1,240104010002,F,30.0,40.0,45.0,40.0,35.0,B,Pass
2,240104010003,M,38.0,38.0,38.0,38.0,38.0,B,Pass
3,240104010004,M,59.0,55.0,57.0,58.0,54.0,A,pass
4,240104010005,M,30.0,30.0,30.0,30.0,30.0,C,Pass
...,...,...,...,...,...,...,...,...,...
81,2520104004,M,24.0,25.0,26.0,27.0,24.0,P,Pass
82,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,2520104006,F,30.0,30.0,30.0,30.0,30.0,B,Pass
84,2520104007,F,45.0,40.0,50.0,48.0,46.0,A,pass
85,2520104008,F,35.0,30.0,40.0,45.0,48.0,B,Pass

## 5. Exporting Data to JSON

JSON (JavaScript Object Notation) is a commonly used format for storing and exchanging structured data.

The `to_json()` function converts a Pandas DataFrame into JSON format.

The `orient="records"` parameter represents each row as a separate JSON object.

In [32]:
df.to_json("EXPORTS/Mldata.json", orient="records", indent=4)

print("Data exported successfully to JSON.")

Data exported successfully to JSON.

### Importing the JSON File

In [33]:
df_json = pd.read_json(
    "EXPORTS/Mldata.json",
    dtype={"ROLL NO.": "string"}
)

df_json

,ROLL NO.,GENDER,SOFTWARE ENGINEER,TOC,COMPUTER NETWORK,MACHINE LEARNING,DATA WAREHOUSE,GRADE,RESULT
0,240104010001,M,30.0,30.0,30.0,30.0,30.0,C,PASS
1,240104010002,F,30.0,40.0,45.0,40.0,35.0,B,Pass
2,240104010003,M,38.0,38.0,38.0,38.0,38.0,B,Pass
3,240104010004,M,59.0,55.0,57.0,58.0,54.0,A,pass
4,240104010005,M,30.0,30.0,30.0,30.0,30.0,C,Pass
...,...,...,...,...,...,...,...,...,...
81,2520104004,M,24.0,25.0,26.0,27.0,24.0,P,Pass
82,<NA>,None,NaN,NaN,NaN,NaN,NaN,None,None
83,2520104006,F,30.0,30.0,30.0,30.0,30.0,B,Pass
84,2520104007,F,45.0,40.0,50.0,48.0,46.0,A,pass
85,2520104008,F,35.0,30.0,40.0,45.0,48.0,B,Pass

## 6. Exporting Data to TSV

TSV stands for Tab-Separated Values. It is similar to CSV, but the values are separated using a tab character (`\t`) instead of a comma.

The `sep="\t"` parameter specifies the tab character as the separator.

In [34]:
df.to_csv(
    "EXPORTS/Mldata.tsv",
    sep="\t",
    index=False
)

print("Data exported successfully to TSV.")

Data exported successfully to TSV.

### Importing the TSV File

In [35]:
df_tsv = pd.read_csv(
    "EXPORTS/Mldata.tsv",
    sep="\t",
    dtype={"ROLL NO.": "string"}
)

df_tsv

,ROLL NO.,GENDER,SOFTWARE ENGINEER,TOC,COMPUTER NETWORK,MACHINE LEARNING,DATA WAREHOUSE,GRADE,RESULT
0,240104010001,M,30.0,30.0,30.0,30.0,30.0,C,PASS
1,240104010002,F,30.0,40.0,45.0,40.0,35.0,B,Pass
2,240104010003,M,38.0,38.0,38.0,38.0,38.0,B,Pass
3,240104010004,M,59.0,55.0,57.0,58.0,54.0,A,pass
4,240104010005,M,30.0,30.0,30.0,30.0,30.0,C,Pass
...,...,...,...,...,...,...,...,...,...
81,2520104004,M,24.0,25.0,26.0,27.0,24.0,P,Pass
82,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,2520104006,F,30.0,30.0,30.0,30.0,30.0,B,Pass
84,2520104007,F,45.0,40.0,50.0,48.0,46.0,A,pass
85,2520104008,F,35.0,30.0,40.0,45.0,48.0,B,Pass

## Result / Conclusion

The Pandas library was successfully used to import and export the student dataset in different file formats.

The following formats were demonstrated:

- Excel (`.xlsx`)
- CSV (`.csv`)
- JSON (`.json`)
- TSV (`.tsv`)

The practical demonstrated how Pandas DataFrames can be converted between different data-storage formats using appropriate import and export functions.